import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_NavBar/NavBar";

export const metadata: Metadata = {
  title: "Map Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        </body>
    </html>
  );
}
